### ISSUE TITLE
HotSpot parser: Blocked thread does not declare monitor

### ISSUE THREAD

**Issue by olivergondza** [olivergondza/dumpling#46]
```
java.lang.IllegalArgumentException: Blocked thread does not declare monitor: >>>
"Reference Handler" daemon prio=10 tid=1238581248 nid=5016
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.ref.ReferenceQueue.enqueue(ReferenceQueue.java:43)
	- locked <0x3ffe4e810> (a java.lang.ref.ReferenceQueue$Lock)
	- locked <0x7feb71638> (a java.lang.ref.Finalizer)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:129)
<<<
```

**Comment by olivergondza** [comment]
Or:
```
java.lang.IllegalArgumentException: Blocked thread does not declare monitor: >>>
"Jenkins-Remoting-Thread-71451" daemon prio=10 tid=47485410174976 nid=11534
   java.lang.Thread.State: BLOCKED (on object monitor)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:113)
	- locked <0x42653c690> (a hudson.remoting.SingleLaneExecutorService)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)

   Locked ownable synchronizers:
	- <0x7f31ff9a0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

<<<
```

**Comment by olivergondza** [comment]
It seems that hotspot updates acquired locks before the thread status, though it does not sound wise to depend on that.

**Comment by olivergondza** [comment]
```
"Jenkins-Remoting-Thread-85956 : IO ID=39102529 : seq#=39102528" daemon prio=10 tid=47483058302976 nid=21476
   java.lang.Thread.State: BLOCKED (on object monitor)
	at hudson.remoting.Channel.send(Channel.java:523)
	- locked <0x41f5de6a8> (a hudson.remoting.Channel)
	at hudson.remoting.ProxyOutputStream$Chunk$1.run(ProxyOutputStream.java:265)
	at hudson.remoting.PipeWriter$1.run(PipeWriter.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
 
   Locked ownable synchronizers:
	- <0x688afea50> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

**Comment by olivergondza** [comment]
```
"Jenkins-cron-thread-8" daemon prio=10 tid=2784872448 nid=13544
   java.lang.Thread.State: BLOCKED (on object monitor)
	at hudson.model.Queue.maintain(Queue.java:1067)
	- locked <0x407008ab8> (a hudson.model.Queue)
	at hudson.model.Queue$MaintainTask.doRun(Queue.java:2089)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
 
   Locked ownable synchronizers:
	- <0x40d21a940> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

**Comment by olivergondza** [comment]
I observed this fixup can cause 2 threads declare to own the same monitor. The hypothesis that it is the lock state that is ahead is supported by the thread state hint "waiting for monitor entry".

```
Timer-288" prio=10 tid=0x000000006d585800 nid=0x4dbc waiting for monitor entry [0x00002ad99daf1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
  at org.fedorahosted.beaker4j.xmlrpc.client.BeakerXmlRpcClient.doRPCall(BeakerXmlRpcClient.java:53)
  - locked <0x0000000407f08830> (a org.apache.xmlrpc.client.XmlRpcClient)
  at org.fedorahosted.beaker4j.xmlrpc.client.BeakerXmlRpcClient.doRPCall(BeakerXmlRpcClient.java:46)
  at org.fedorahosted.beaker4j.xmlrpc.client.BeakerXmlRpcClient.execute(BeakerXmlRpcClient.java:42)
  at org.fedorahosted.beaker4j.remote_model.RemoteBeakerObject.callOnBeaker(RemoteBeakerObject.java:21)
  at org.fedorahosted.beaker4j.remote_model.BeakerTask.getInfo(BeakerTask.java:26)
  at org.jenkinsci.plugins.beakerbuilder.TaskWatchdog.run(TaskWatchdog.java:67)
  - locked <0x00000005cbdec0c0> (a org.jenkinsci.plugins.beakerbuilder.TaskWatchdog)
  at java.util.TimerThread.mainLoop(Timer.java:512)
  at java.util.TimerThread.run(Timer.java:462)

   Locked ownable synchronizers:
  - None
```
