### ISSUE TITLE
Unable to parse hexadecimal identifier in upper range

### ISSUE THREAD

**Issue by olivergondza** [olivergondza/dumpling#71]
Dumpling managed to fit all those identifies into types that are wide enough, though the number represent a unsigned value. When parsing, it is considered to be signed and might not fit into the type.

```
java.lang.NumberFormatException: For input string: "ffffffffe2875c0a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:76)
	at java.lang.Long.parseLong(Long.java:604)
	at com.github.olivergondza.dumpling.factory.ThreadDumpFactory.createLock(ThreadDumpFactory.java:355)
	at com.github.olivergondza.dumpling.factory.ThreadDumpFactory.initStacktrace(ThreadDumpFactory.java:213)
	at com.github.olivergondza.dumpling.factory.ThreadDumpFactory.thread(ThreadDumpFactory.java:167)
	at com.github.olivergondza.dumpling.factory.ThreadDumpFactory.fromStream(ThreadDumpFactory.java:112)
	at com.github.olivergondza.dumpling.factory.ThreadDumpFactoryTest.reparse(ThreadDumpFactoryTest.java:974)
	at com.github.olivergondza.dumpling.factory.ThreadDumpFactoryTest.parseOutputProducedByJvmRuntimeFactory(ThreadDumpFactoryTest.java:675)
...
```

Reproduced on macosx.

**Comment by olivergondza** [comment]
Can this happen for Dumpling human readable nid output?
